AnalysisType: rule
Filename: aws_security_configuration_change.py
RuleID: AWS.CloudTrail.SecurityConfigurationChange
DisplayName: Account Security Configuration Changed
Enabled: true
LogTypes:
  - AWS.CloudTrail
Tags:
  - AWS
Severity: Medium
Reports:
  MITRE ATT&CK:
    - Defense Evasion:Stop Security Monitoring
Description: An account wide security configuration was changed.
Runbook: >
  Verify that this change was planned. If not, revert the change and update the access control policies to ensure this doesn't happen again.
Reference: reference.link
SummaryAttributes:
  - eventName
  - userAgent
  - sourceIpAddress
  - recipientAccountId
  - p_any_aws_arns
Tests:
  -
    Name: Security Configuration Changed
    ExpectedResult: true
    Log:
      {
          "awsRegion": "us-west-2",
          "eventID": "1111",
          "eventName": "DeleteTrail",
          "eventSource": "cloudtrail.amazonaws.com",
          "eventTime": "2019-01-01T00:00:00Z",
          "eventType": "AwsApiCall",
          "eventVersion": "1.05",
          "readOnly": false,
          "recipientAccountId": "123456789012",
          "requestID": "1111",
          "requestParameters": {
              "name": "example-trail"
          },
          "responseElements": null,
          "sourceIPAddress": "111.111.111.111",
          "userAgent": "Mozilla/2.0 (compatible; NEWT ActiveX; Win32)",
          "userIdentity": {
              "accessKeyId": "1111",
              "accountId": "123456789012",
              "arn": "arn:aws:sts::123456789012:assumed-role/example-role/example-user",
              "invokedBy": "cloudformation.amazonaws.com",
              "principalId": "1111",
              "sessionContext": {
                  "attributes": {
                      "creationDate": "2019-01-01T00:00:00Z",
                      "mfaAuthenticated": "true"
                  },
                  "sessionIssuer": {
                      "accountId": "123456789012",
                      "arn": "arn:aws:iam::123456789012:role/example-role",
                      "principalId": "1111",
                      "type": "Role",
                      "userName": "example-role"
                  },
                  "webIdFederationData": {}
              },
              "type": "AssumedRole"
          }
      }
  -
    Name: Security Configuration Not Changed
    ExpectedResult: false
    Log:
      {
          "awsRegion": "us-west-2",
          "eventID": "1111",
          "eventName": "DescribeTrail",
          "eventSource": "cloudtrail.amazonaws.com",
          "eventTime": "2019-01-01T00:00:00Z",
          "eventType": "AwsApiCall",
          "eventVersion": "1.05",
          "readOnly": false,
          "recipientAccountId": "123456789012",
          "requestID": "1111",
          "requestParameters": {
              "name": "example-trail"
          },
          "responseElements": null,
          "sourceIPAddress": "111.111.111.111",
          "userAgent": "Mozilla/2.0 (compatible; NEWT ActiveX; Win32)",
          "userIdentity": {
              "accessKeyId": "1111",
              "accountId": "123456789012",
              "arn": "arn:aws:sts::123456789012:assumed-role/example-role/example-user",
              "invokedBy": "cloudformation.amazonaws.com",
              "principalId": "1111",
              "sessionContext": {
                  "attributes": {
                      "creationDate": "2019-01-01T00:00:00Z",
                      "mfaAuthenticated": "true"
                  },
                  "sessionIssuer": {
                      "accountId": "123456789012",
                      "arn": "arn:aws:iam::123456789012:role/example-role",
                      "principalId": "1111",
                      "type": "Role",
                      "userName": "example-role"
                  },
                  "webIdFederationData": {}
              },
              "type": "AssumedRole"
          }
      }
  -
    Name: Non Security Configuration Change
    ExpectedResult: false
    Log:
      {
          "awsRegion": "us-west-2",
          "eventID": "1111",
          "eventName": "PutPolicy",
          "eventSource": "iam.amazonaws.com",
          "eventTime": "2019-01-01T00:00:00Z",
          "eventType": "AwsApiCall",
          "eventVersion": "1.05",
          "readOnly": false,
          "recipientAccountId": "123456789012",
          "requestID": "1111",
          "requestParameters": {
              "name": "example-trail"
          },
          "responseElements": null,
          "sourceIPAddress": "111.111.111.111",
          "userAgent": "Mozilla/2.0 (compatible; NEWT ActiveX; Win32)",
          "userIdentity": {
              "accessKeyId": "1111",
              "accountId": "123456789012",
              "arn": "arn:aws:sts::123456789012:assumed-role/example-role/example-user",
              "invokedBy": "cloudformation.amazonaws.com",
              "principalId": "1111",
              "sessionContext": {
                  "attributes": {
                      "creationDate": "2019-01-01T00:00:00Z",
                      "mfaAuthenticated": "true"
                  },
                  "sessionIssuer": {
                      "accountId": "123456789012",
                      "arn": "arn:aws:iam::123456789012:role/example-role",
                      "principalId": "1111",
                      "type": "Role",
                      "userName": "example-role"
                  },
                  "webIdFederationData": {}
              },
              "type": "AssumedRole"
          }
      }
  -
    Name: Security Configuration Not Changed - Error
    ExpectedResult: false
    Log:
      {
          "awsRegion": "us-west-2",
          "errorCode": "ConflictException",
          "eventID": "1111",
          "eventName": "DeleteTrail",
          "eventSource": "cloudtrail.amazonaws.com",
          "eventTime": "2019-01-01T00:00:00Z",
          "eventType": "AwsApiCall",
          "eventVersion": "1.05",
          "readOnly": false,
          "recipientAccountId": "123456789012",
          "requestID": "1111",
          "requestParameters": {
              "name": "example-trail"
          },
          "responseElements": null,
          "sourceIPAddress": "111.111.111.111",
          "userAgent": "Mozilla/2.0 (compatible; NEWT ActiveX; Win32)",
          "userIdentity": {
              "accessKeyId": "1111",
              "accountId": "123456789012",
              "arn": "arn:aws:sts::123456789012:assumed-role/example-role/example-user",
              "invokedBy": "cloudformation.amazonaws.com",
              "principalId": "1111",
              "sessionContext": {
                  "attributes": {
                      "creationDate": "2019-01-01T00:00:00Z",
                      "mfaAuthenticated": "true"
                  },
                  "sessionIssuer": {
                      "accountId": "123456789012",
                      "arn": "arn:aws:iam::123456789012:role/example-role",
                      "principalId": "1111",
                      "type": "Role",
                      "userName": "example-role"
                  },
                  "webIdFederationData": {}
              },
              "type": "AssumedRole"
          }
      }
  -
    Name: Security Configuration Changed - Allowlisted User
    ExpectedResult: false
    Log:
      {
          "awsRegion": "us-west-2",
          "eventID": "1111",
          "eventName": "ExampleEvent",
          "eventSource": "cloudtrail.amazonaws.com",
          "eventTime": "2019-01-01T00:00:00Z",
          "eventType": "AwsApiCall",
          "eventVersion": "1.05",
          "readOnly": false,
          "recipientAccountId": "123456789012",
          "requestID": "1111",
          "requestParameters": {
              "name": "example-trail"
          },
          "responseElements": null,
          "sourceIPAddress": "111.111.111.111",
          "userAgent": "Mozilla/2.0 (compatible; NEWT ActiveX; Win32)",
          "userIdentity": {
              "accessKeyId": "1111",
              "accountId": "123456789012",
              "arn": "arn:aws:sts::123456789012:assumed-role/example-role/example-user",
              "invokedBy": "cloudformation.amazonaws.com",
              "principalId": "1111",
              "sessionContext": {
                  "attributes": {
                      "creationDate": "2019-01-01T00:00:00Z",
                      "mfaAuthenticated": "true"
                  },
                  "sessionIssuer": {
                      "accountId": "123456789012",
                      "arn": "arn:aws:iam::123456789012:role/example-role",
                      "principalId": "1111",
                      "type": "Role",
                      "userName": "ExampleUser"
                  },
                  "webIdFederationData": {}
              },
              "type": "AssumedRole"
          }
      }

