name: Generate versions file

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - "main"
      # add branch name here to test workflow on PR
      - "mcr/EPD-4377-versioning-in-pr"

jobs:
  generate-versions:
    if: github.repository == 'panther-labs/panther-analysis'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pipenv
          make install

      - name: Generate .versions.yml file
        run: |
          echo "Running on commit: ${{ github.sha }}"
          make generate-versions

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6.3.0
        with:
          gpg_private_key: ${{ secrets.PANTHER_BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PANTHER_BOT_GPG_PRIVATE_KEY_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Branch and commit changes
        run: |
          git config --global user.email "github-service-account-automation@panther.io"
          git config --global user.name "panther-bot-automation"
          git switch -c auto-update-versions-${{ github.sha }}
          git add .
          git commit -m "Auto-generated .versions.yml file"
          git push origin auto-update-versions-${{ github.sha }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7.0.8
        with:
          token: ${{ secrets.PANTHER_BOT_AUTOMATION_TOKEN }}
          # commit-message: "Auto-generated .versions.yml file"
          # committer: panther-bot-automation <github-service-account-automation@panther.io>
          author: panther-bot-automation <github-service-account-automation@panther.io>
          sign-commits: true
          base: main
          branch: auto-update-versions-${{ github.sha }}
          delete-branch: true
          title: "Auto-generated .versions.yml file"
          body: |
            This PR was automatically generated by the [generate-versions-file workflow](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).

            It updates the `.versions.yml` file based on the latest commit to main.

            **Commit:** ${{ github.sha }}
          labels: |
            automation
            versions
          draft: false

