name: Generate Indexes (Internal)

on:
  pull_request:
    branches:
      - develop
    paths-ignore:
      - 'indexes/**'

permissions:
  contents: write

jobs:
  generate-indexes:
    runs-on: ubuntu-latest
    if: github.repository == 'panther-labs/panther-analysis' && github.actor != 'dependabot[bot]'
    permissions:
      id-token: write
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.PANTHER_BOT_AUTOMATION_TOKEN }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          fetch-depth: 0
          token: ${{ env.GITHUB_TOKEN || github.token }}
      - name: Install Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 #v6.2.0
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip3 install -r ./.scripts/requirements.txt
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@e89d40939c28e39f97cf32126055eeae86ba74ec #v6.3.0
        with:
          gpg_private_key: ${{ secrets.PANTHER_BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PANTHER_BOT_GPG_PRIVATE_KEY_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Generate indexes
        run: python3 ./.scripts/generate_indexes.py
      - name: Commit Indexes
        continue-on-error: true # This is to ensure that the workflow does not fail if there are no changes to commit
        run: |
          git config --global user.email "github-service-account-automation@panther.io"
          git config --global user.name "panther-bot-automation"
          git fetch origin ${{ github.event.pull_request.head.ref }}:${{ github.event.pull_request.head.ref }}
          git checkout ${{ github.event.pull_request.head.ref }}
          git add ./indexes
          git commit -S -m "Update indexes"
          git push origin ${{ github.event.pull_request.head.ref }}