name: Generate versions file

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - "main"

jobs:
  generate-versions:
    if: github.repository == 'panther-labs/panther-analysis'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pipenv
          make install

      - name: Generate .versions.yml file
        run: |
          echo "Running on commit: ${{ github.sha }}"
          make generate-versions

      - name: Check for changes
        id: check-for-changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Changes detected"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "No changes to commit"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@e89d40939c28e39f97cf32126055eeae86ba74ec #v6.3.0
        with:
          gpg_private_key: ${{ secrets.PANTHER_BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PANTHER_BOT_GPG_PRIVATE_KEY_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Branch and commit changes
        if: steps.check-for-changes.outputs.has_changes == 'true'
        run: |
          git config --global user.email "github-service-account-automation@panther.io"
          git config --global user.name "panther-bot-automation"
          git switch main
          git switch -c auto-update-versions-${{ github.sha }}
          git add .
          git commit -m "Auto-generated .versions.yml file"
          git push origin auto-update-versions-${{ github.sha }}

      # peter-evans/create-pull-request@v7.0.8 was not working with git signing, so using gh cli instead
      - name: Create Pull Request
        if: steps.check-for-changes.outputs.has_changes == 'true'
        env:
          GH_TOKEN: ${{ secrets.PANTHER_BOT_AUTOMATION_TOKEN }} # needed for gh cli
        run: |
          gh pr create \
            --title "Auto-generated .versions.yml file" \
            --body 'This PR was automatically generated by the [generate-versions-file workflow](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).' \
            --base main
